### ISSUE TITLE
GPU Acceleration?

### ISSUE THREAD

**Issue by ankushKun** [game-de-it/rg35xx#2]
Regarding the Desktop OS

When running some graphic intensive application through chromium, it seems there is no GPU acceleration, even though RG35XXSP has a dual-core Mali-G31 MP2, it is not being used.

Any plans for adding GPU acceleration support?

**Comment by game-de-it** [comment]
I'm not a Chromium developer, so I don't really understand the situation.

I think it would be more reliable to access the URL below, collect information, and ask questions in the Chromium development community.

chrome://gpu

**Comment by ankushKun** [comment]
Is there some cli tool I can use to check if GPU is available on OS level? 

Doing neofetch doesnot give any GPU details.
Asking the chromium community without knowing if GPU is available would be pointless

**Comment by game-de-it** [comment]
I think the Chromium developers or people knowledgeable about it would know whether Chromium can make the GPU available.
It might be possible to solve the problem with a setting similar to about:config in Firefox.

As for whether the GPU is available at the OS level, it goes without saying that if something is displayed on the LCD display, the GPU is being used.

I don't know whether Chromium then uses libmali, or if it uses a different mechanism to use the GPU.(^^;)
